### ISSUE TITLE
`dyld: Library not loaded: @rpath/libpcre2-8.0.dylib`

### ISSUE THREAD

**Issue by omus** [JuliaBinaryWrappers/Git_jll.jl#2] opened 2020-06-02 18:36 UTC
Using Git_jll v2.26.1+0 on macOS 10.14.6 with Julia 1.3.1:
```julia
julia> using Git_jll

julia> git() do git_path
           read(`$git_path ls-remote --tags https://github.com/JuliaLang/julia`, String)
       end
dyld: Library not loaded: @rpath/libpcre2-8.0.dylib
  Referenced from: /Users/omus/.julia/artifacts/592d01a4f901d3676d38410fd6520d335612c691/bin/git
  Reason: Incompatible library version: git requires version 10.0.0 or later, but libpcre2-8.0.dylib provides version 8.0.0
ERROR: failed process: Process(`/Users/omus/.julia/artifacts/592d01a4f901d3676d38410fd6520d335612c691/bin/git ls-remote --tags https://github.com/JuliaLang/julia`, ProcessSignaled(6)) [0]
```

**Comment by iamed2** [comment] 2020-06-02 18:37
What version of Julia?

**Comment by omus** [comment] 2020-06-02 18:38
Updated description

**Comment by giordano** [comment] 2020-06-02 18:38
Duplicate of https://github.com/JuliaPackaging/Yggdrasil/issues/1063

**Closed** 2020-06-18 20:05 UTC
